---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and jq
    apt:
      name: 
        - apache2
        - php
      update_cache: yes
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: remove jq package
    apt:
      name:
        - jq
      state: absent
